apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::010438494949:role/jenkins-role-ecr
      username: jenkins
      groups:
        - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::010438494949:user/admin-user
      username: admin
      groups:
        - system:masters